public enum CombatAction
{
    NONE, ATTACK, LIFE_POTION, MANA_POTION, 
    SKILL_STAB, SKILL_SHURIKEN, SKILL_DOUBLESTRIKE,SKILL_SPEEDSTRIKE,
    SKILL_VERTICALSTRIKE, SKILL_AVENGER, SKILL_SPLIT, SKILL_EXECUTION,
    SKILL_CHARGE, SKILL_HEAL, SKILL_ENERGYSHOT, SKILL_FIRESHOT,
    SKILL_MANABOMB, SKILL_ANNIHILATE, SKILL_SHADOWSTRIKE, SKILL_REPLICATE,
    LASER, DOUBLE_LASER, TRIPLE_ENERGYBALL, FIREBALL, THROW_SLASH, FULL_HEAL,
    WASP_STING, WASP_LASER, CHARGE_SHOT, LIFESTEAL
}
