public enum InteractionID
{
    NONE,
    // General actions
    EXIT_UP, EXIT_DOWN, EXIT_RIGHT, EXIT_LEFT,
    // Entrance Room
    ENTRANCE_NPC1, ENTRANCE_NPC2, ENTRANCE_NPC3,
    // First Room ("Basar")
    BASAR_NPC1, BASAR_NPC2, BASAR_NPC3,
    // Second Room ("Market")
    MARKET_NPC1, MARKET_NPC2, MARKET_NPC3,
    // Human Gate Room
    HGATE_GATE_ENTRY, HGATE_NPC1, HGATE_NPC2,
    // Pub
    PUB_NPC1, PUB_NPC2, PUB_NPC3, PUB_NPC4,
    // ARMORY
    ARMORY_NPC1, ARMORY_NPC2, ARMORY_NPC3,
    // LIBRARY
    LIBRARY_NPC1, LIBRARY_NPC2, LIBRARY_NPC3, LIBRARY_BOOKS,
    // UPPER_HALL
    SECRET,
    // MONSTER_GATE
    MGATE_GATE_ENTRY, MGATE_NPC1, MGATE_NPC2, MGATE_NPC3, MGATE_NOTE, TRAINING_ENTRY,
    // PRE_DARK
    PREDARK_NPC1, PREDARK_NPC2, PREDARK_EXIT,
    // DARK_GATE
    DGATE_GUARD, DGATE_NPC, DGATE_MERCHANT, DGATE_MERCHANT2, DGATE_GATE_ENTRY
}